# Generated by Django 4.2.6 on 2023-12-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_webpage_topics_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='topics_name',
            new_name='topic_name',
        ),
    ]
